"""
fetch_logos.py — Download most-recent ESPN team logos for every manager.
Tries 2025 → 2024 → ... → 2020 per owner, takes first accessible URL.
Outputs:
  images/logos/{slug}.{ext}   — downloaded logo files
  js/logoData.js              — JS const TEAM_LOGOS = { "Owner Name": "images/logos/..." }
Usage: python3 fetch_logos.py
"""

import os, re, json, urllib.request
from dotenv import load_dotenv
from espn_api.football import League

load_dotenv()
LEAGUE_ID = int(os.getenv("LEAGUE_ID"))
ESPN_S2   = os.getenv("ESPN_S2")
SWID      = os.getenv("SWID")
YEARS     = list(range(2025, 2019, -1))  # 2025 → 2020

os.makedirs("images/logos", exist_ok=True)

def slugify(name):
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

def try_download(canonical_name, url):
    """Try to download url; return local path on success, None on failure."""
    slug = slugify(canonical_name)
    clean = url.split('?')[0]
    ext = clean.rsplit('.', 1)[-1].lower()
    if ext not in ('png', 'jpg', 'jpeg', 'gif', 'svg'):
        ext = 'png'
    local = f"images/logos/{slug}.{ext}"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            ct = resp.headers.get('Content-Type', '')
            if 'html' in ct:
                return None
            data = resp.read()
        # Minimal sanity check — real images are at least a few hundred bytes
        if len(data) < 200:
            return None
        with open(local, 'wb') as f:
            f.write(data)
        return local
    except Exception:
        return None

# Alias map so Alyssa Gilliam == Alyssa Mirto
ALIASES = {'Alyssa Gilliam': 'Alyssa Mirto', 'Tomas McGrath': 'Thomas McGrath'}

# Collect all owner → [candidate (year, url)] pairs
candidates = {}  # canonical_name → [(year, url), ...]

for year in YEARS:
    try:
        league = League(league_id=LEAGUE_ID, year=year, espn_s2=ESPN_S2, swid=SWID)
        for t in league.teams:
            info  = t.owners[0] if t.owners else {}
            raw   = f"{info.get('firstName','')} {info.get('lastName','')}".strip()
            canon = ALIASES.get(raw, raw)
            url   = t.logo_url or ''
            if not url:
                continue
            if canon not in candidates:
                candidates[canon] = []
            candidates[canon].append((year, url))
    except Exception as e:
        print(f"  {year}: skipped ({e})")

# For each owner, try years newest→oldest until a download succeeds
logo_map = {}
for canon, items in sorted(candidates.items()):
    # items already in newest-first order since YEARS is descending
    success = False
    for year, url in items:
        path = try_download(canon, url)
        if path:
            logo_map[canon] = path
            print(f"  OK  {canon:30s} ← {year}  {url[:60]}")
            success = True
            break
    if not success:
        print(f"  FAIL {canon} — no accessible logo found")

# Write logo_map.json
with open('logo_map.json', 'w') as f:
    json.dump(logo_map, f, indent=2, sort_keys=True)

# Write js/logoData.js
js_lines = ['/* Auto-generated by fetch_logos.py — do not edit manually */',
            'const TEAM_LOGOS = {']
for name, path in sorted(logo_map.items()):
    js_lines.append(f'  {json.dumps(name)}: {json.dumps(path)},')
js_lines.append('};')
with open('js/logoData.js', 'w') as f:
    f.write('\n'.join(js_lines) + '\n')

print(f'\nDone. {len(logo_map)} logos.  js/logoData.js written.')
